# See: https://docs.readthedocs.io/en/latest/yaml-config.html
version: 2

formats:
  - epub
  - pdf

python:
  version: "3.7"
  install:
    - method: pip
      path: .
      install:
        - requirements: docs/doc_requirements.txt
      extra_requirements:
        - docs
  system_packages: true