# See: https://docs.readthedocs.io/en/latest/yaml-config.html
version: 2

formats:
  - epub
  - pdf

python:
  version: "3.7"
  install:
    - requirements: docs/doc_requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
        - pyorient @ git+https://github.com/orientechnologies/pyorient.git
  system_packages: true